vim.api.nvim_create_user_command("TabLabel", require("tabscope.tablabel").tabline, {})
vim.api.nvim_create_user_command("TabRename", require("tabscope.tablabel").rename_tab, {})
vim.api.nvim_create_user_command("TabBufList", require("tabscope.bufferlist").list, {})
vim.api.nvim_create_user_command("TabBufNext", require("tabscope.bufferlist").next, {})
vim.api.nvim_create_user_command("TabBufPrev", require("tabscope.bufferlist").prev, {})
vim.api.nvim_create_user_command("TabCwd", function()
  require("tabscope.bufferlist").cwd({ scope = "tab" })
end, {})
vim.api.nvim_create_user_command("TabCwdGlobal", function()
  require("tabscope.bufferlist").cwd({ scope = "global" })
end, {})
vim.api.nvim_create_user_command("TabOpen", function()
  require("tabscope.bufferlist").open({ scope = "tab" })
end, {})
vim.api.nvim_create_user_command("TabOpenGlobal", function()
  require("tabscope.bufferlist").open({ scope = "global" })
end, {})
